### ISSUE TITLE
Замечания lw5

### ISSUE THREAD

**Issue by ivklgn** [guccisquad/lab5#1]
**Сценарий приложения:**
Предлагаю следующий вариант работы приложения:
1) пользователь заходит на страницу мессенджера и видит только поле ввода имени для чата - мессенджер скрыт
2) вводит имя, проверяем на ошибки
3) если всё ок - то показываем мессенджер.
p.s при обновлении страницы - пользователь по идее должен ввести имя снова. (мессенджер снова скрывается)
Материал: https://docs.google.com/presentation/d/1KMBKBwdzCPeIGjNQLPdLsYWXmOQRF5mOw7th65z6FF4/edit

**JS:**
1. Для проставления и отображения времени попробуйте посмотреть в сторону moment.js
2. Подумайте о том, как хранить сообщения в localStorage? каким образом их отображать в чате.

**Взаимодействие:**
1. При вводе сообщения и успешной отправке имеет смысл очищать поле ввода сообщения
2. При добавлении сообщения в мессанджере требуется проскролить вниз к последнему сообщению блок.

kQ=0,4

**Comment by guccisquad** [comment]
> Для проставления и отображения времени попробуйте посмотреть в сторону moment.js

Сделано.

> При вводе сообщения и успешной отправке имеет смысл очищать поле ввода сообщения

Сделано.

> При добавлении сообщения в мессанджере требуется проскролить вниз к последнему сообщению блок

Сделано.

**Comment by ivklgn** [comment]
1. По нажатию <enter> поле очищается, но переход на новую строку в вводе происходит.
- попробовать сделать проверку с использованием функции trim и длинны сообщения length.
2. Для того чтобы сделать два события для одного действия можно использовать делегирование событий (jquery)
3. Идея с localStorage:
- сообщения хранятся в массиве объектов
- при создании сообщения модифицируем объект хранилища с сообщениями
- добавляем событие 'storage' (https://habrahabr.ru/post/317586/) 
- в теле события 'storage' берем значение localStorage и обновляем в мессенджере

**Comment by guccisquad** [comment]
с localStorage все равно непонятки остались. Отправленное сообщение сначала записывается в него, потом выводиться в чат. Проблема с "перепиской" из 2 вкладок. Сообщения видны только после перезагрузки страницы ($(document).ready(function())). Какое событие установить чтобы обновлялось сразу же? Пока ничего кроме как сделать через ajax не придумал.10.02.2018, 14:55, "Kalagin Ivan" <notifications@github.com>:
По нажатию  поле очищается, но переход на новую строку в вводе происходит.


попробовать сделать проверку с использованием функции trim и длинны сообщения length.


Для того чтобы сделать два события для одного действия можно использовать делегирование событий (jquery)
Идея с localStorage:


сообщения хранятся в массиве объектов
при создании сообщения модифицируем объект хранилища с сообщениями
добавляем событие 'storage' (https://habrahabr.ru/post/317586/)
в теле события 'storage' берем значение localStorage и обновляем в мессенджере
